version: "3"
services:
  user_service:
    build: docker/tests/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - backend
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    networks:
      - backend
networks:
  backend:
  frontend: