version: "3"
services:
  user_service:
    build: Docker/tests/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    networks:
      - backend
  tests:
    build:
      context: .
      dockerfile: Docker/tests/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/opt/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    networks:
      - backend
networks:
  backend:
  frontend:
volumes:
  postgres_data: